<?php
$mapping = null;
$disableClustering = null;
$basemapProvider = null;

$hasMapping = false;
$hasFeatures = false;
switch (get_class($resource)) {
    case 'Omeka\Api\Representation\ItemRepresentation':
        $itemsQuery = ['id' => $resource->id()];
        $mappingResponse = $this->api()->searchOne('custom_mappings', ['item_id' => $resource->id()]);
        $mapping = $mappingResponse->getContent();
        $hasMapping = $mappingResponse->getTotalResults();
        $hasFeatures = $this->api()->search('custom_mapping_features', ['item_id' => $resource->id(), 'limit' => 0])->getTotalResults();
        break;
    case 'Omeka\Api\Representation\ItemSetRepresentation':
        $itemsQuery = ['item_set_id' => $resource->id()];
        $hasFeatures = $this->api()->search('custom_mapping_features', ['item_set_id' => $resource->id(), 'limit' => 0])->getTotalResults();
        break;
    default:
        return;
}
// Don't render the map if there is no mapping data.
if (!$hasMapping && !$hasFeatures) {
    return;
}

if ($this->status()->isSiteRequest()) {
    $featuresUrl = $this->url('site/custom-mapping', ['controller' => 'index', 'action' => 'get-features'], true);
    $featurePopupContentUrl = $this->url('site/custom-mapping', ['controller' => 'index', 'action' => 'get-feature-popup-content'], true);
    $disableClustering = $this->siteSetting('mapping_disable_clustering');
    $basemapProvider = $this->siteSetting('mapping_basemap_provider');
} else {
    $featuresUrl = $this->url('admin/custom-mapping', ['controller' => 'index', 'action' => 'get-features']);
    $featurePopupContentUrl = $this->url('admin/custom-mapping', ['controller' => 'index', 'action' => 'get-feature-popup-content']);
}

$this->headLink()->appendStylesheet($this->assetUrl('node_modules/leaflet/dist/leaflet.css', 'CustomMapping'));
$this->headLink()->appendStylesheet($this->assetUrl('node_modules/leaflet.markercluster/dist/MarkerCluster.css', 'CustomMapping'));
$this->headLink()->appendStylesheet($this->assetUrl('node_modules/leaflet.markercluster/dist/MarkerCluster.Default.css', 'CustomMapping'));
$this->headLink()->appendStylesheet($this->assetUrl('node_modules/leaflet.fullscreen/Control.FullScreen.css', 'CustomMapping'));
$this->headLink()->appendStylesheet($this->assetUrl('css/mapping.css', 'CustomMapping'));

$this->headScript()->appendFile($this->assetUrl('node_modules/leaflet/dist/leaflet.js', 'CustomMapping'));
$this->headScript()->appendFile($this->assetUrl('node_modules/leaflet.markercluster/dist/leaflet.markercluster-src.js', 'CustomMapping'));
$this->headScript()->appendFile($this->assetUrl('node_modules/leaflet.fullscreen/Control.FullScreen.js', 'CustomMapping'));
$this->headScript()->appendFile($this->assetUrl('node_modules/leaflet-providers/leaflet-providers.js', 'CustomMapping'));
$this->headScript()->appendFile($this->assetUrl('node_modules/Leaflet.Deflate/dist/L.Deflate.js', 'CustomMapping'));

$this->headScript()->appendFile($this->assetUrl('js/MappingModule.js', 'CustomMapping'));
$this->headScript()->appendFile($this->assetUrl('js/mapping-show.js', 'CustomMapping'));
$this->headScript()->appendFile($this->assetUrl('js/control.fit-bounds.js', 'CustomMapping'));
?>


<!-- CLIENT SIDE -->
<div id="mapping-section" class="section">

    <!-- Check if it is admin or client side -->
    <script>
        window.mappingIsAdmin = <?php echo $this->status()->isAdminRequest() ? 'true' : 'false'; ?>;
    </script>

        <div id="mapping-map" style="height:700px;" data-mapping="<?php echo $this->escapeHtml(json_encode($mapping)); ?>"
            data-disable-clustering="<?php echo $disableClustering ? '1' : '0'; ?>"
            data-basemap-provider="<?php echo $basemapProvider ?? ''; ?>"
            data-features-url="<?php echo $this->escapeHtml($featuresUrl); ?>"
            data-feature-popup-content-url="<?php echo $this->escapeHtml($featurePopupContentUrl); ?>"
            data-items-query="<?php echo $this->escapeHtml(json_encode($itemsQuery)); ?>" data-features-query="[]">
        </div>
        <!-- Sidebar -->
        <div id="mapping-view-sidebar" class="sidebar">
            <a href="#" class="sidebar-close o-icon-close">
                <span class="screen-reader-text">
                    <?php echo $this->translate('Close'); ?>
                </span>
            </a>

            <div class="sidebar-content">
            
                    <!-- HEADER -->
                    <div class="sidebar-header">
                        <span class="sidebar-pin"></span>
                        <h2 class="sidebar-title"></h2>
                    </div>

                    <!-- DESCRIPTION -->
                    <div class="sidebar-description"></div>

                    <!-- IMAGE -->
                    <div class="sidebar-media"></div>

            </div>
        </div>


</div>