<!-- This is what is showing inside of the popup -->
<?php
$label = $feature->label();
$description = $feature->description();
$media = $feature->media();
$item = $feature->item();
$color = $feature->markerColor();
?>
<span class="group-type" style="<?php echo $color ? 'color:' . $this->escapeHtmlAttr($color) : ''; ?>">

    <h2 class="sidebar-title">
        <?php echo ($label) ? $this->escapeHtml($label) : $this->translate('Item'); ?>
    </h2>

</span>

<span class="group-value">

    <!-- <?php echo $item->link($item->displayTitle(null, $this->lang()), null, ['target' => '_blank']); ?> -->

    <?php if ($media): ?>
        <?php echo $this->thumbnail($media, 'medium'); ?>
    <?php endif; ?>

    <?php if (!empty($description)): ?>
        <p class="sidebar-description">
            <?php echo $this->escapeHtml($description); ?>
        </p>
    <?php endif; ?>

</span>